import Sidebar from "@/components/layouts/sidebar"
import type { Metadata } from "next"
import { Alegreya, Inter } from "next/font/google"
import "./globals.css"
import { Providers } from "./providers"


const inter = Inter({ subsets: ["latin"] })
const alegreya = Alegreya({ subsets: ["latin"] })
// const oswald = PT_Sans({ weight: "400" | "700" })

export const metadata: Metadata = {
	title: "Said Babaiev",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning={true}>
			<body className={`${inter.className} bg-bg text-text`}>
				<Providers attribute="class" defaultTheme="light" enableSystem>
					<div>
						<div className="container px-8 md:px-18 xl:px-56 mx-auto flex flex-row">
							<header className="basis-2/4 pr-16">
								<Sidebar />
							</header>
							<main className="basis-2/4">
								{children}
							</main>
						</div>
					</div>
				</Providers>
			</body>
		</html>
	)
}
