// import { ThemeSwitcher } from "@/components/ThemeSwitcher"
import Sidebar from "@/components/layouts/sidebar"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Providers } from "./providers"


const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Said Babaiev",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning={true}>
			<body className={`${inter.className} bg-white dark:bg-black text-black dark:text-white`}>
				<Providers attribute="class" defaultTheme="light" enableSystem>
					<div className="container px-8 md:px-18 xl:px-56 mx-auto flex flex-row">
						<header className="basis-2/4 pr-16">
							{/* <ThemeSwitcher /> */}
							<Sidebar />
						</header>
						<main className="basis-2/4">
							{children}
						</main>
					</div>
				</Providers>
			</body>
		</html>
	)
}
